<?php

namespace Container9yINWxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YRkHh0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y_RkHh0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y_RkHh0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'App\\MessageHandler\\ClearRefreshTokenFromDatabaseHandler', 'getClearRefreshTokenFromDatabaseHandlerService', true],
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', true],
        ], [
            'handler' => 'App\\MessageHandler\\ClearRefreshTokenFromDatabaseHandler',
            'messageBus' => '?',
        ]);
    }
}
