<?php

namespace Container9yINWxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTargetRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TargetRepository' shared autowired service.
     *
     * @return \App\Repository\TargetRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/TargetRepository.php';

        return $container->privates['App\\Repository\\TargetRepository'] = new \App\Repository\TargetRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
