<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RefreshToken extends \App\Entity\RefreshToken implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'refreshToken' => [parent::class, 'refreshToken', null],
        "\0".'*'."\0".'username' => [parent::class, 'username', null],
        "\0".'*'."\0".'valid' => [parent::class, 'valid', null],
        'id' => [parent::class, 'id', null],
        'refreshToken' => [parent::class, 'refreshToken', null],
        'username' => [parent::class, 'username', null],
        'valid' => [parent::class, 'valid', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
