<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Target extends \App\Entity\Target implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'ageRange' => [parent::class, 'ageRange', null],
        "\0".parent::class."\0".'brief' => [parent::class, 'brief', null],
        "\0".parent::class."\0".'civilStatus' => [parent::class, 'civilStatus', null],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null],
        "\0".parent::class."\0".'geolocatedContext' => [parent::class, 'geolocatedContext', null],
        "\0".parent::class."\0".'housingData' => [parent::class, 'housingData', null],
        "\0".parent::class."\0".'housingStatus' => [parent::class, 'housingStatus', null],
        "\0".parent::class."\0".'housingType' => [parent::class, 'housingType', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'ageRange' => [parent::class, 'ageRange', null],
        'brief' => [parent::class, 'brief', null],
        'civilStatus' => [parent::class, 'civilStatus', null],
        'gender' => [parent::class, 'gender', null],
        'geolocatedContext' => [parent::class, 'geolocatedContext', null],
        'housingData' => [parent::class, 'housingData', null],
        'housingStatus' => [parent::class, 'housingStatus', null],
        'housingType' => [parent::class, 'housingType', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
