<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Brief extends \App\Entity\Brief implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'businessModel' => [parent::class, 'businessModel', null],
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isSigned' => [parent::class, 'isSigned', null],
        "\0".parent::class."\0".'landingPageUrl' => [parent::class, 'landingPageUrl', null],
        "\0".parent::class."\0".'leverage' => [parent::class, 'leverage', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'needKitMail' => [parent::class, 'needKitMail', null],
        "\0".parent::class."\0".'needLP' => [parent::class, 'needLP', null],
        "\0".parent::class."\0".'participatingCompanies' => [parent::class, 'participatingCompanies', null],
        "\0".parent::class."\0".'project' => [parent::class, 'project', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'target' => [parent::class, 'target', null],
        "\0".parent::class."\0".'totalBudget' => [parent::class, 'totalBudget', null],
        "\0".parent::class."\0".'unitPrice' => [parent::class, 'unitPrice', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'volume' => [parent::class, 'volume', null],
        'businessModel' => [parent::class, 'businessModel', null],
        'comment' => [parent::class, 'comment', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'id' => [parent::class, 'id', null],
        'isSigned' => [parent::class, 'isSigned', null],
        'landingPageUrl' => [parent::class, 'landingPageUrl', null],
        'leverage' => [parent::class, 'leverage', null],
        'name' => [parent::class, 'name', null],
        'needKitMail' => [parent::class, 'needKitMail', null],
        'needLP' => [parent::class, 'needLP', null],
        'participatingCompanies' => [parent::class, 'participatingCompanies', null],
        'project' => [parent::class, 'project', null],
        'status' => [parent::class, 'status', null],
        'target' => [parent::class, 'target', null],
        'totalBudget' => [parent::class, 'totalBudget', null],
        'unitPrice' => [parent::class, 'unitPrice', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'user' => [parent::class, 'user', null],
        'volume' => [parent::class, 'volume', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
