<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Company extends \App\Entity\Company implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'companyRegistrationNumber' => [parent::class, 'companyRegistrationNumber', null],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageSize' => [parent::class, 'imageSize', null],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null],
        "\0".parent::class."\0".'logoFile' => [parent::class, 'logoFile', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        "\0".parent::class."\0".'vatNumber' => [parent::class, 'vatNumber', null],
        "\0".parent::class."\0".'zipcode' => [parent::class, 'zipcode', null],
        'address' => [parent::class, 'address', null],
        'city' => [parent::class, 'city', null],
        'companyRegistrationNumber' => [parent::class, 'companyRegistrationNumber', null],
        'country' => [parent::class, 'country', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'id' => [parent::class, 'id', null],
        'imageSize' => [parent::class, 'imageSize', null],
        'logo' => [parent::class, 'logo', null],
        'logoBase64' => [parent::class, 'logoBase64', null],
        'logoFile' => [parent::class, 'logoFile', null],
        'logoUrl' => [parent::class, 'logoUrl', null],
        'name' => [parent::class, 'name', null],
        'roles' => [parent::class, 'roles', null],
        'users' => [parent::class, 'users', null],
        'vatNumber' => [parent::class, 'vatNumber', null],
        'zipcode' => [parent::class, 'zipcode', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
