<?php

namespace ContainerK9PXoPY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackingPixelGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\TrackingPixelGenerator' shared autowired service.
     *
     * @return \App\Service\TrackingPixelGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TrackingPixelGenerator.php';

        $container->services['App\\Service\\TrackingPixelGenerator'] = $instance = new \App\Service\TrackingPixelGenerator();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Service\\TrackingPixelGenerator', $container));

        return $instance;
    }
}
