<?php

namespace ContainerZnsDjNa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QuhhJxUService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.QuhhJxU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QuhhJxU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'default' => ['privates', 'App\\Scheduler\\ClearRefreshTokenScheduler', 'getClearRefreshTokenSchedulerService', true],
        ], [
            'default' => 'App\\Scheduler\\ClearRefreshTokenScheduler',
        ]);
    }
}
