<?php

namespace ContainerZnsDjNa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeverageRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Repository\LeverageRepository' shared autowired service.
     *
     * @return \App\Repository\LeverageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/LeverageRepository.php';

        return $container->privates['App\\Repository\\LeverageRepository'] = new \App\Repository\LeverageRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
