<?php

namespace ContainerZnsDjNa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenApiFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\OpenApi\OpenApiFactory' shared autowired service.
     *
     * @return \App\OpenApi\OpenApiFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/OpenApi/OpenApiFactory.php';

        return $container->privates['App\\OpenApi\\OpenApiFactory'] = new \App\OpenApi\OpenApiFactory(($container->privates['App\\OpenApi\\OpenApiFactory.inner'] ?? $container->load('getOpenApiFactory_InnerService')));
    }
}
