<?php

namespace ContainerSszQNE1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L8PeLb_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l8PeLb.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l8PeLb.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'mailService' => ['privates', 'App\\Service\\MailUpdatePassword', 'getMailUpdatePasswordService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'uploadHandler' => ['services', 'vich_uploader.upload_handler', 'getVichUploader_UploadHandlerService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', false],
        ], [
            'entityManager' => '?',
            'logger' => '?',
            'mailService' => 'App\\Service\\MailUpdatePassword',
            'serializer' => '?',
            'uploadHandler' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
