<?php

namespace ContainerSszQNE1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBriefSelectionRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\BriefSelectionRepository' shared autowired service.
     *
     * @return \App\Repository\BriefSelectionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/BriefSelectionRepository.php';

        return $container->privates['App\\Repository\\BriefSelectionRepository'] = new \App\Repository\BriefSelectionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
