<?php

namespace ContainerSszQNE1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailUpdatePasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MailUpdatePassword' shared autowired service.
     *
     * @return \App\Service\MailUpdatePassword
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MailUpdatePassword.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\MailUpdatePassword'])) {
            return $container->privates['App\\Service\\MailUpdatePassword'];
        }

        return $container->privates['App\\Service\\MailUpdatePassword'] = new \App\Service\MailUpdatePassword($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
