<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZnsDjNa\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZnsDjNa/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerZnsDjNa.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerZnsDjNa\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerZnsDjNa\App_KernelTestDebugContainer([
    'container.build_hash' => 'ZnsDjNa',
    'container.build_id' => '78d2086a',
    'container.build_time' => 1730907226,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZnsDjNa');
