<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK9PXoPY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK9PXoPY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK9PXoPY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK9PXoPY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK9PXoPY\App_KernelDevDebugContainer([
    'container.build_hash' => 'K9PXoPY',
    'container.build_id' => 'fde41ef0',
    'container.build_time' => 1732218258,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK9PXoPY');
